chore(deps): bump Angular to 14.2 from 14.0 to address several CVEs
ReadAlongs/Studio-Web-archived pull request #19
Opened 2022-11-24 19:31 UTC by joanise

These Dependabot alerts are all fixed by upgrading Angular to 14.2 and re-creating package-lock.json from scratch:
https://github.com/ReadAlongs/Studio-Web/security/dependabot/2 https://github.com/ReadAlongs/Studio-Web/security/dependabot/4 https://github.com/ReadAlongs/Studio-Web/security/dependabot/5 https://github.com/ReadAlongs/Studio-Web/security/dependabot/8

Tested on my machine with automated tests and manual testing.

CI passes too, on Node 14, 16 and 18.

2022-11-24 19:35 UTC, joanise commented
@roedoejet @dhdaines @deltork This PR will require rerunning `npm install` when you update. But Angular 14.2 seems to update a bunch of packages for CVEs without changing any functionality. I've already moved Web-Component/packages/angular-component to Angular 14.2 since it is not in active use yet, but I want to give you a warning before updating this one, via this PR.

2022-12-07 16:42 UTC, dhdaines commented
This seems good to me!  Thanks for the unit test example!

2022-12-07 16:44 UTC, joanise commented
@dhdaines Ready to merge, then?

2022-12-07 17:26 UTC, roedoejet requested changes
All looks great to me, and gets rid of all the security stuff as you say. The only thing is you've changed around some of the grids, which fixes some things, like going from this:

![image](https://user-images.githubusercontent.com/14815080/206248357-9b3a50c4-334a-4bd4-8cb5-6738de40f772.png)

to this: 

![image](https://user-images.githubusercontent.com/14815080/206248401-34c5ffcd-29bd-4d67-bc0f-057376871b5d.png)

which is awesome! but it also has the save button offset from the right side as noted in a comment. Can you rix this? (might need some additional css. Thanks @joanise !

2022-12-07 17:26 UTC, roedoejet commented on src/app/upload/upload.component.html
> +                        <div class="col-6 col-md-8 col-lg-9">
Why change this? It now appears a bit offset from the right edge: 
Original: ![image](https://user-images.githubusercontent.com/14815080/206247945-dbfe1b31-da08-4157-b692-21d97a00f240.png)

This PR: 
![image](https://user-images.githubusercontent.com/14815080/206248020-c8d64dad-0fa2-4cda-89da-dd99f27951d4.png)

2022-12-07 17:47 UTC, dhdaines commented
> @dhdaines Thanks! Ready to merge, then?

No problem for me, merge when you're ready (and see Aidan's comments above)

2022-12-07 20:21 UTC, joanise commented on src/app/upload/upload.component.html
> +                        <div class="col-6 col-md-8 col-lg-9">
On larger screens, the Save button is nicely centered under the Write and File buttons, but it's not so nice on smaller screens. I'll find better setting for smaller screens but I like my large screen view.
While I'm at it, I'll also try to fix this:
![image](https://user-images.githubusercontent.com/33264708/206287374-3d9bd21d-29ae-4bd8-a2a6-94c1e2bbb2ac.png)

2022-12-07 20:26 UTC, joanise commented on src/app/upload/upload.component.html
> +                        <div class="col-6 col-md-8 col-lg-9">
So I suggest keeping this:
![image](https://user-images.githubusercontent.com/33264708/206288099-026a9cfd-a596-42b4-a804-c8fa1ae218fd.png)
but fixing this:
![image](https://user-images.githubusercontent.com/33264708/206288205-b666220a-1a5c-473b-8f54-a29eb9ab5de9.png)
by aligning it to the right when the screen gets smaller.

2022-12-07 21:45 UTC, joanise commented
@roedoejet updated and ready for re-reviewing.
md+:
![image](https://user-images.githubusercontent.com/33264708/206301967-d9642ab3-5633-44d5-bf48-a60af2627c31.png)
md:
![image](https://user-images.githubusercontent.com/33264708/206302923-dca581a0-8d35-49cc-9e2e-d9902fdf719e.png)
sm-:
![image](https://user-images.githubusercontent.com/33264708/206303075-df7b3480-2837-4441-984d-25520fa84ae8.png)

2022-12-07 21:46 UTC, joanise commented
And, for the record, I hate HTML, even in 2022 with all the frameworks and libraries. All this formatting nonsense, half of it not working at any given time, and never the same half from one day to the next. Bleh.

2022-12-07 21:48 UTC, joanise commented on src/app/upload/upload.component.html
> +                        <div class="col-6 col-md-8 col-lg-9">
And nevermind this, it's now always on the right.

2022-12-07 21:57 UTC, dhdaines commented
> And, for the record, I hate HTML, even in 2022 with all the frameworks and libraries. All this formatting nonsense, half of it not working at any given time, and never the same half from one day to the next. Bleh.

It's really CSS that's the problem... decades later you still can't reliably do certain types of layouts that are easy to achieve with tables, and the whole point of CSS layouts was supposed to be to avoid using markup for presentation purposes...

2022-12-07 22:03 UTC, joanise commented
> > And, for the record, I hate HTML, even in 2022 with all the frameworks and libraries. All this formatting nonsense, half of it not working at any given time, and never the same half from one day to the next. Bleh.
> 
> It's really CSS that's the problem... decades later you still can't reliably do certain types of layouts that are easy to achieve with tables, and the whole point of CSS layouts was supposed to be to avoid using markup for presentation purposes...

That's a fair point, all the stuff I'm fighting with is either classes which trigger css, or `style=""` which is just more css inlined. In the Coursera course too, I always find it annoying how to instructor adds this and that class and you're just supposed to know why. I have to experiment quite a bit to make sense of stuff.

2022-12-08 17:20 UTC, merged