Add a text format dialog, plus misc other improvements
ReadAlongs/Studio-Web-archived pull request #26
Opened 2022-12-12 21:48 UTC by joanise

- Add a dialog to explain our plain text format (Fixes #12)
 - improve the layout of the text section
 - get bootstrap from npm since we're already using npm for this project
 - remove deprecated tilde imports in css
 - remove unused quill dependency

2022-12-13 23:48 UTC, roedoejet requested changes
This is fantastic @joanise - you definitely are picking up Angular, I'm really impressed! I only have a couple minor suggestions with the formatting of the actual message in the dialog but everything else looks good!

2022-12-13 23:48 UTC, roedoejet commented on package.json
> +        "bootstrap": "^5.2.3",
I'm not a huge fan of bootstrap - but I get that that's just me. How big is this dependency? Do you know how much it bloats the build?

2022-12-13 23:48 UTC, roedoejet commented on src/app/app.module.ts
> +    MatToolbarModule,
Nice! All the right injections!

2022-12-13 23:48 UTC, roedoejet commented on src/app/text-format-dialog/text-format-dialog.component.html
> +Sent 2 in the second paragraph.
I would say "this is sentence 2 in the second paragraph". I know it's a small point, but makes it more readable. Actually, I would change all of them to the same format:

```
This is sentence one in paragraph one on page one.
This is sentence two in paragraph one on page one.

This is sentence one in paragraph two on page one.
This is sentence two in paragraph two on page one.


This is sentence one in paragraph one on page two.
```

And I would limit it to just the above (ie a more minimal example). This is a great idea though!

2022-12-14 15:42 UTC, dhdaines commented on package.json
> +        "bootstrap": "^5.2.3",
it looks like it takes up about half of the output css file, though this is not a precise estimate.  what are we using it for aside from doing a CSS reset?

2022-12-14 15:43 UTC, dhdaines commented on src/app/text-format-dialog/text-format-dialog.component.html
> +Sent 2 in the second paragraph.
Agreed, it should say "sentence two" or "second sentence", not necessary to use digits

2022-12-14 15:45 UTC, dhdaines commented
Looks good overall!  If you want to tweak the example text a bit that would be good.  For bootstrap perhaps it should be a different PR as it was already there, and we would want to make sure it isn't used by anything or that we have a smaller alternative...

2022-12-14 21:49 UTC, joanise commented on package.json
> +        "bootstrap": "^5.2.3",
Hey, I didn't actually add this dependency, I just made it explicit. It was already there in a hidden, tucked-away kind way. Its presence made me complain quite a bit because the equivalent angular classes is what I expected, but bootstrap's what the code uses. 
It was hidden in file `src/bootstrap.min.css` presumably precompiled and copied from some other project just like that.
The next refactoring I'd love to do is eliminate bootstrap completely and just use Angular Material, I think that would be much nicer. But that's a bigger project for a latter PR.

2022-12-14 21:55 UTC, joanise commented on src/app/text-format-dialog/text-format-dialog.component.html
> +Sent 2 in the second paragraph.
Yeah, I was hesitant at first reading this comment, but I think I agree.

My only reason to hesitate is the cell phone view:
![image](https://user-images.githubusercontent.com/33264708/207723238-ef5f7269-ea3f-424f-8779-85ff0d567a2c.png)
but I just figured out you can scroll left and right by clicking in the `pre` text and pushing it right or left. That would have been obvious if I had been testing on an actual phone, but I didn't realize it since I was testing in the phone simulation view in Chrome.

2022-12-14 22:01 UTC, joanise commented on src/app/app.module.ts
> +    MatToolbarModule,
> Looks good overall! If you want to tweak the example text a bit that would be good. For bootstrap perhaps it should be a different PR as it was already there, and we would want to make sure it isn't used by anything or that we have a smaller alternative...

Well , this PR combines four unrelated commits, so once we're happy with my dialog, I'll fast-forward merge it anyway.

Onto the agenda: remove bootstrap.

2022-12-14 22:03 UTC, roedoejet commented on package.json
> +        "bootstrap": "^5.2.3",
hahaha! that's funny. ok. maybe it was me then? maybe I'm just talking to myself then 😅 - fwiw I totally agree with you Eric!

2022-12-14 22:04 UTC, joanise commented
> Looks good overall! If you want to tweak the example text a bit that would be good. For bootstrap perhaps it should be a different PR as it was already there, and we would want to make sure it isn't used by anything or that we have a smaller alternative...

Well, this PR has four unrelated commits, so I'm going to fast-forward merge it anyway, once the dialog example is OK.

For bootstrap, it's a straight swap, and I think in a future PR we should remove it altogether.

2022-12-14 22:14 UTC, joanise commented on src/app/text-format-dialog/text-format-dialog.component.html
> +Sent 2 in the second paragraph.
Just pushed an update, using example Aidan's text. Thanks for the feedback!

2022-12-14 22:35 UTC, joanise commented on package.json
> +        "bootstrap": "^5.2.3",
> it looks like it takes up about half of the output css file, though this is not a precise estimate. what are we using it for aside from doing a CSS reset?

Oops, I missed that comment @dhdaines. We're only using it for its css classes defining the 12 column responsive layout thing. Totally replaceable by Angular's equivalent thing.

2022-12-14 22:37 UTC, joanise commented on package.json
> +        "bootstrap": "^5.2.3",
Except that I'm sure replacing it will require a lot of patience and/or swearing, as always seems to be the case with layout stuff.

2022-12-15 14:00 UTC, joanise commented
Man, sorry for the million questions... I'm working on polishing the text―I figure even if we change how we do i18n, we'll still keep this text, so I'm not wasting my time―and I noticed another potential issue: on the Privacy and data sovereignty policy dialog, I want to translate "Ok" as "D'accord", but if there was another "Ok" button elsewhere, that one might be better translated as "Valider". Does this tool allow use to have the same message translated in two different context-sensitive way?

2022-12-15 14:36 UTC, merged